### ISSUE TITLE
Add caplog fixture for example pytest

### ISSUE THREAD

**Issue by hampusnasstrom** [FAIRmat-NFDI/cookiecutter-nomad-plugin#32]
We should add a caplog fixture for pytest to assert that there are no errors in the log during the parsing and normalization of the test archives in the tests. Something like what @ka-sarthak added here: https://github.com/FAIRmat-NFDI/nomad-measurements/pull/115/commits/f00ef7624f15c4ce9de9c15872f36060180add73

**Comment by blueraft** [comment]
Is this something that's going to useful for all of the plugins? @lauri-codes what do you think?

Regarding the implementation itself, the snippet in `nomad-measurements` might not work under all circumstances. This can cause issues when there are other methods that might deal with logging outputs. See the nomad code for this: 

https://github.com/nomad-coe/nomad/blob/264b6d832705581f2aaa9cbc5459603fbd89869d/tests/conftest.py#L77-L95

And structlog reference: https://www.structlog.org/en/stable/testing.html

**Comment by lauri-codes** [comment]
I think it will be quite useful. But can't we just use the existing fixtures from `nomad`? There is already: `log_output`, `no_warn`, `with_error`, etc. Just a matter of making sure we have some relatively versatile fixture that could be parametrized to assert for the existence/non existence of certain log levels.

**Comment by JosePizarro3** [comment]
> We should add a caplog fixture for pytest to assert that there are no errors in the log during the parsing and normalization of the test archives in the tests

This is interesting indeed. For me it would be cool if we can retrieve `error`, `warning`, `info` to test these cases (including the negative ones).

**Comment by ka-sarthak** [comment]
@lauri-codes something like this could parameterize the fixture to capture specified log levels.

```py
@pytest.fixture(
    name='caplog',
    scope='function',
)
def fixture_caplog(request):
    """
    Extracts log messages from the logger and raises an assertion error if the specified
    log levels in the `request.param` are found.
    """
    caplog = LogCapture()
    processors = structlog.get_config()['processors']
    old_processors = processors.copy()

    try:
        processors.clear()
        processors.append(caplog)
        structlog.configure(processors=processors)
        yield caplog
        for record in caplog.entries:
            if record['log_level'] in request.param:
                assert False, record
    finally:
        processors.clear()
        processors.extend(old_processors)
        structlog.configure(processors=processors)


@pytest.mark.parametrize(
    'caplog',
    ['error', 'critical'],
    indirect=True,
)
def test_fixture_caplog(caplog):
    logger = structlog.get_logger()

    logger.error('This is an error message.')
    logger.critical('This is a critical message.')
```

**Comment by lauri-codes** [comment]
Looks like this would be a very handy tool for many. I would proceed by making this into an issue in the nomad-FAIR repo, where we could introduce a better, more generic log fixture (and the importing of which should not require any extra dependencies). I think that is a more sustainable way than adding these utilities in the plugin template. Does that sound good?

**Comment by JosePizarro3** [comment]
> Looks like this would be a very handy tool for many. I would proceed by making this into an issue in the nomad-FAIR repo, where we could introduce a better, more generic log fixture (and the importing of which should not require any extra dependencies). I think that is a more sustainable way than adding these utilities in the plugin template. Does that sound good?

Indeed. Actually, I think we should have a more robust way of handling logger messages. These are key to understand the entries as well, especially when doing big data.

**Comment by JosePizarro3** [comment]
But, can we get the logger when querying entries?

**Comment by lauri-codes** [comment]
Not sure what you mean: could you give an example? You can definitely filter the logs by `entry_id`, but I'm not sure if this is what you mean.

**Comment by JosePizarro3** [comment]
Let's chat in the Gitlab, otherwise this conversation will get lost.

But in short, I would like to know whether it is possible to retrieve the list of logs with their levels passed to the logger when you query data and receive some entries. This way, you can check whether there was some error or warning which affects your analysis / ML.

I think the issue is that I don't know (or we don't have) how to manage the logger properly, or whether this has any impact beyond debugging.

**Comment by blueraft** [comment]
https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/issues/2131
