### ISSUE TITLE
Tests fail in templated repository

### ISSUE THREAD

**Issue by hampusnasstrom** [FAIRmat-NFDI/cookiecutter-nomad-plugin#6]
I just created a repository and the pipeline is failing when I commit the code directly after running cruft and the move script: https://github.com/hampusnasstrom/nomad-sintering-plugin-test/actions/runs/9050375910/job/24865647308

**Comment by hampusnasstrom** [comment]
@blueraft it looks like it's looking for a nested folder somehow: `'/home/runner/work/nomad-sintering-plugin-test/nomad-sintering-plugin-test/tests/schema_packages/data/test.archive.yaml'`

**Comment by hampusnasstrom** [comment]
Ah, I now see that you have a PR on tests already. Will this fix this problem as well?

**Comment by blueraft** [comment]
That's unrelated, it only tests whether the correct files are generated.

Regarding this issue, a quick fix might be just using `tests` folder explicitly.

Instead of:

```python
test_file = os.path.join(os.path.dirname(__file__), 'data', 'test.archive.yaml')
```

```python
test_file = os.path.join('tests' , 'data', 'test.archive.yaml')
```

The tests in general are not entirely updated for the new plugin system though so some of the assertions may just fail.

**Comment by hampusnasstrom** [comment]
Okay, I will demo this on Wednesday and people will follow along and create their own plugins so it would be good if we can make sure that the 2 pipelines are running without errors or in the worst case disable them for now.
